apiVersion: v1
kind: ConfigMap
metadata:
  name: pdns-rec-config
data:
  recursor.yml: |
    # PowerDNS Recursor configuration file
    incoming:
      allow_from:
      - 0.0.0.0/0
      port: 53

    logging:
      disable_syslog: true
      loglevel: {{PDNS_RECURSOR_LOGLEVEL}}
      quiet: {{PDNS_RECURSOR_QUIET}}

    recordcache:
      max_negative_ttl: 1
    
    recursor:
      forward_zones_recurse:
      - zone: {{DOMAIN}}
        recurse: true
        forwarders:
        - pdns-auth-udp
      - zone: .
        recurse: true
        forwarders:
        - {{PUBLIC_RESOLVER}}:53
      system_resolver_ttl: 60
    
    webservice:
      address: 0.0.0.0
      allow_from:
      - 0.0.0.0/0
      port: 8082
      webserver: true