apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdns-recursor
  labels:
    app: pdns-recursor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pdns-recursor
  template:
    metadata:
      labels:
        app: pdns-recursor
    spec:
      initContainers:
      - name: init-secrets
        image: busybox
        command:
        - sh
        - -c
        - |
          # Copy the config file from configMap
          cp /etc/pdns-config/recursor.yml /etc/powerdns/recursor.d/recursor.yml

          # Generate the secrets.yml file
          echo "webservice:" > /etc/powerdns/recursor.d/secrets.yml
          echo "  api_key: $(cat /etc/pdns/secrets/api-key)" >> /etc/powerdns/recursor.d/secrets.yml
          echo "  password: $(cat /etc/pdns/secrets/webserver-password)" >> /etc/powerdns/recursor.d/secrets.yml
          echo "Secrets and config initialized successfully."
        volumeMounts:
        - name: pdns-rec-secrets-volume
          mountPath: /etc/pdns/secrets
          readOnly: true
        - name: pdns-rec-configmap
          mountPath: /etc/pdns-config
          readOnly: true
        - name: pdns-rec-shared
          mountPath: /etc/powerdns/recursor.d
      containers:
      - name: pdns-recursor
        image: powerdns/pdns-recursor-51:5.1.3
        ports:
        - containerPort: 53
          protocol: TCP
        - containerPort: 53
          protocol: UDP
        - containerPort: 8082
          protocol: TCP
        volumeMounts:
        - name: pdns-rec-shared
          mountPath: /etc/powerdns/recursor.d

      volumes:
      - name: pdns-rec-shared
        emptyDir: {}
      - name: pdns-rec-secrets-volume
        secret:
          secretName: pdns-rec-secrets
      - name: pdns-rec-configmap
        configMap:
          name: pdns-rec-config