apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdns-recursor
  labels:
    app: pdns-recursor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pdns-recursor
  template:
    metadata:
      labels:
        app: pdns-recursor
    spec:
      containers:
      - name: pdns-recursor
        image: powerdns/pdns-recursor-51:5.1.0-alpha1
        ports:
        # - containerPort: 53
        #   protocol: TCP
        - containerPort: 53
          protocol: UDP
        - containerPort: 8082
          protocol: TCP
        volumeMounts:
        - name: pdns-rec-config-volume
          mountPath: /etc/powerdns/recursor.d/pdns.conf
          subPath: pdns.conf
      volumes:
      - name: pdns-rec-config-volume
        configMap:
          name: pdns-rec-config
