apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: powerdns-rec-udp
spec:
  entryPoints:
  - dns-udp
  routes:
  - services:
    - name: pdns-rec-udp
      port: 53
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: powerdns-rec-api
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`pdns-rec.{{DOMAIN}}`)
      kind: Rule
      services:
        - name: pdns-rec-api
          port: 8082
  tls: {}