apiVersion: v1
kind: ConfigMap
metadata:
  name: pdns-auth-config
data:
  pdns.conf: |
    include-dir=/etc/powerdns/pdns.d
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pdns-auth-config-general
data:
  pdns-general.conf: |
    # PowerDNS Authoritative configuration file
    launch=gpgsql
    gpgsql-host=pdns-postgres-db
    gpgsql-port=5432
    gpgsql-dbname=dns
    gpgsql-user=pdns
    
    # General
    local-port=53
    
    # Webserver
    webserver=yes
    webserver-address=0.0.0.0
    webserver-allow-from=0.0.0.0/0
    webserver-port=8081

    # API
    api=yes