apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdns-auth
  labels:
    app: pdns-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pdns-auth
  template:
    metadata:
      labels:
        app: pdns-auth
    spec:
      containers:
      - name: pdns-auth
        image: powerdns/pdns-auth-49:4.9.0
        ports:
        # - containerPort: 53
        #   protocol: TCP
        - containerPort: 53
          protocol: UDP
        - containerPort: 8081
          protocol: TCP
        volumeMounts:
        - name: pdns-auth-config-volume
          mountPath: /etc/powerdns/pdns.conf
          subPath: pdns.conf
      volumes:
      - name: pdns-auth-config-volume
        configMap:
          name: pdns-auth-config
