apiVersion: v1
kind: Service
metadata:
  name: pdns-auth-udp
spec:
  selector:
    app: pdns-auth
  ports:
  - protocol: UDP
    port: 53
    targetPort: 53
---
apiVersion: v1
kind: Service
metadata:
  name: pdns-auth-api
spec:
  selector:
    app: pdns-auth
  ports:
  - protocol: TCP
    port: 8081